server:
  port: 8080

logging:
  level:
    root: debug


# no load balancing
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth-resource:
      path: /resource/**
      url: http://localhost:6061/
    oauth:
      path: /oauth/**
      url: http://localhost:6060/

#security:
#  oauth2:
#    resource:
#      jwt:
#        key-value: 123